### ISSUE TITLE
Rerunning an existing App Engine Standard env(Flex) run config after removing <env>flex still tries to deploy to flex

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1236] opened 2017-02-09 18:32 UTC
steps to reproduce
 
1. take an standard app
2. add <env>flex</env> to appengine-web.xml
3. create a deployment run config and deploy.
4. remove <env>flex</env> from appengine-web.xml
5. re-run deployment run config **without** opening the config for edit
6. notice that the deployment still tries to deploy to flex.
7. open the run config for edit, not that it's set to standard when viewed, and save
8. deployment now works as intended.

**Comment by etanshaul** [comment] 2017-03-01 20:05
@patflynn I'm not currently able to reproduce this

However, my suspicion is that this is related to a discussion I had with @joaoandremartins on the flex facet PR:

I was, at one point, able to reproduce something similar and the cause seemed to have something to do with the IJ's auto-save feature: it seemed that non-source files weren't auto-committed "immediately", although I am not sure what the commit strategy is. By doing an explicit save (file -> save) the problem was overcome. This is still not great because no-one really does explicit saving with intellij but I don't know if we can do more here.

**Closed** 2017-06-21 18:19 UTC
Labels: App Engine, App Engine Flex, bug, google-cloud-tools-plugin
