### ISSUE TITLE
Error running locally 

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#2027] opened 2018-04-12 19:12 UTC
(Please ensure you are running the latest version of Cloud Tools for IntelliJ with _Help > Check for Updates_.)

- Cloud Tools for IntelliJ version: master
- Google Cloud SDK version _(run `gcloud version` on the command line)_: (automanaged?)
- OS:linux

**What did you do?**
checked out https://github.com/patflynn/cloud-debugger-idea-sample in 2018.1
imported maven
added framework support
run locally
**What did you expect to see?**
local run to work 
**What did you see instead?**
```
Error running 'Google App Engine Standard Local Server': Error running Google App Engine Dev Server. Exception occurred : com.google.cloud.tools.appengine.api.AppEngineException Exception message : java.nio.file.NoSuchFileException: /usr/local/google/home/paflynn/IdeaProjects/ct4ij-cloud-debugger-demo/target/hello-1.0-SNAPSHOT/WEB-INF/appengine-web.xm
(screenshots are helpful)
```
![screenshot from 2018-04-12 15-12-15](https://user-images.githubusercontent.com/7862557/38698691-f0cd9b7e-3e63-11e8-941a-c2cafc8b0cb7.png)

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by etanshaul** [comment] 2018-04-12 19:19
@patflynn could not reproduce this in 2018.1. My steps:

1) Clone the project (directly from IDEA using import from VCS -> git)
2) After the project is opened, accept the popup for adding App Engine framework support, and import maven
3) Configure the project SDK
4) run ->

![image](https://user-images.githubusercontent.com/1735744/38699006-ddde0df4-3e64-11e8-9b4e-f76d225cc94d.png)

**Comment by etanshaul** [comment] 2018-04-30 18:01
closing since it was not reproducible - @patflynn feel free to reopen if its still a problem

**Closed by etanshaul** 2018-04-30 18:01 UTC
