### ISSUE TITLE
Use autogenerated datastore indexes for deploy

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-intellij#1616] opened 2017-08-23 15:03 UTC
See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2309#issuecomment-324280383 for full discussion.

We need to validate what our tooling does and make sure that we honor the expected behavior.

**Comment by chanseokoh** [comment] 2017-08-23 23:25
AppCfg staging combines `WEB-INF/datastore-indexes.xml` and `WEB-INF/appengine-generated/datastore-indexes-auto.xml` into a single `index.yaml` (although this may result in duplicate index entries in `index.yaml`). Therefore, if we can run AppCfg staging on a directory where the dev appserver runs, I believe deploying the auto-gen indexes is automatic and we don't need to do anything special. This may not be difficult to implement in build tools, as they could just do both local run and deployment based on their build output directory; the directory could be a single source of truth for every operation, which is persisted across multiple operations until `mvn/gradle clean`.

However, the problem in IDEs is probably that it is difficult to designate a certain dev server work directory as a single "canonical" directory for local run and deploy. Users may run several dev appservers simultaneously in IDEs, and to achieve this, IDEs would maintain separate work directories for each dev server run. (After all, you don't want multiple servers concurrently modifying the auto-gen index XML.) The question of which work directory `gcloud app deploy` should pick and use cannot readily be answered.

One might propose a workaround of preventing multiple dev appservers from running simultaneously for a single app in IDEs, but she will soon notice this is not feasible when considering multi-module local run scenarios. One app could be included in different multi-module sets.

Also, whatever directory will be chosen as a "canonical" directory in IDEs, that directory should have the same lifecycle as that of the project build lifecycle and not that of a dev server, to match the behavior of the current build tools. That is, the "canonical" directory should be cleared only when cleaning the project. (That is, build tools will continue to use the same `datastore-indexes-auto.xml` in their build output directory, and the file is cleared only after `mvn/gradle clean`.)

**Comment by nkibler** [comment] 2017-08-25 14:35
There's a lot to parse here and in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2309. It seems like this requires a non-trivial design and might benefit from a doc shared between the IDEs. WDYT?

**Comment by etanshaul** [comment] 2017-09-01 18:11
missed the comments here.

@chanseokoh whats Eclipse's status on this?
@nkibler +1

**Comment by chanseokoh** [comment] 2017-09-02 00:38
No progress on the Eclipse side. The issue (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2309) says it all. We run a dev appserver on a tmp directory, which is different from the directory we use to deploy, which means the auto-gen index file will get lost.

**Comment by nkibler** [comment] 2017-09-12 15:18
I've confirmed that for IntelliJ, the DevAppServer runs on the exploded war directory, which will place the auto-generated Datastore indexes file in:

```
<project_dir>/target/<maven_artifact_war_dir>/WEB-INF/appengine-generated/datastore-indexes-auto.xml
```

When deploying, using either the exploded WAR artifact or the Maven project artifact will work, assuming `mvn clean` was not run between the DevAppServer run and the deployment. However, the `Update dos, dispatch, cron, queues, and datastore indexes` checkbox **must** be checked in the deployment configuration.

For reference, here are the relevant deployment logs when that checkbox **is** checked:

> ********************************************************
> Reading application configuration data...
> Sep 12, 2017 11:00:44 AM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
> INFO: Successfully processed /[REDACTED]/appengine-java-guestbook-multiphase/final/target/guestbook-1.0-SNAPSHOT/WEB-INF/appengine-generated/datastore-indexes-auto.xml
> *********************************
> 
> ...
> 
> Configurations to update:
> 
> descriptor:      [/[REDACTED]/WEB-INF/appengine-generated/index.yaml]
> type:            [datastore indexes]
> target project:  [REDACTED]

When the checkbox **is not** selected, that last section prefixed with _Configurations to update_ is not logged.


Given all of this, it seems like the Cloud Tools for IntelliJ plugin does correctly deploy this auto-generated indexes file when the aforementioned checkbox is checked in the deployment configuration. I'm marking this closed since there is no additional work required.

**Closed by nkibler** 2017-09-12 15:18 UTC
Labels: App Engine

**Comment by patflynn** [comment] 2017-09-12 16:52
Great! Thanks for testing this out Nate!
