### ISSUE TITLE
High rates of user reported deployment failure.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#1241] opened 2017-02-13 16:29 UTC
Over half of app engine standard deployment failures are reporting:

"Deployment failed due to an unexpected error while staging the project."

as the cause.   Staging should very rarely fail. 

We're also seeing a consistently high rate of:

"Deployment failed with exit code: 1 Please make sure that you are using the latest version of the Google Cloud SDK. Run ''gcloud components update'' to update the SDK. (See: https://cloud.google.com/sdk/gcloud/reference/components/update.)"

This requires some digging since I would expect the rate of this error to go down over time.

**Comment by etanshaul** [comment] 2017-05-24 18:08
@patflynn to check analytics again

**Comment by nkibler** [comment] 2017-06-26 13:46
Duplicate of #1509.

**Closed** 2017-06-26 13:46 UTC
Labels: App Engine, bug, Deployment, google-cloud-tools-plugin, high priority

**Comment by AdamSHurwitz** [comment] 2018-05-15 07:44
I'm receiving this error "**Deployment failed with exit code: 1...**" How do I identify the root of the issue?

**Comment by patflynn** [comment] 2018-05-15 14:08
Hi @AdamSHurwitz, could you file a [new issue](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/new) including the information mentioned in the template?

thx.
