### ISSUE TITLE
Project selector doesn't return all projects

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#858] opened 2016-09-01 15:45 UTC
Our project selector uses the default page size for retrieving projects.  That size is documented [here](https://cloud.google.com/resource-manager/reference/rest/v1/projects/list) as being 'appropriate'.  Appropriate in our case appears to be in the 70s-80s.  

The Project selector really needs to be engineered to robustly support users with arbitrarily large amounts of projects.  For now bumping the page size into the 100s (200?) might be a reasonable short term solution.

**Comment by patflynn** [comment] 2016-09-01 15:57
actually NM. We're setting the large page size in gcloud-intellij. I was looking at the Android Studio code.

We still need a better model for large project sizes, but the short term fix is unnecessary.

**Comment by nkibler** [comment] 2017-05-30 20:27
I have a change drafted that dynamically loads pages of projects with a configurable size (e.g. 50) as the user scrolls and needs to see more. The problem is sorting: the Cloud resource manager API to list projects returns them in an unspecified order and you cannot provide your own sorting scheme: https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list

This would mean all of the projects in the list would be in a random order. I could re-sort after another fetch, but it would likely cause new projects to be inserted further up the list and the user could completely miss them, so it's not a valid approach.

If we want to sacrifice ordering for the paging solution, I can create a PR. Otherwise, I'll close this as WAI, since as of now, it does repeatedly call list until there are no more results upfront.

**Comment by etanshaul** [comment] 2017-05-30 20:33
That's unfortunate that we can't control the sorting.

> since as of now, it does repeatedly call list until there are no more results upfront.

Maybe I'm misunderstanding, but I thought now we are hardcoding some arbitrary large page size (its been a while since I've looked at this)?

**Comment by nkibler** [comment] 2017-05-30 20:34
It's a bit of both: the page size is 300 (which is quite large) and it repeatedly calls list again just in case: https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/resources/GoogleUserModelItem.java#L152

**Comment by etanshaul** [comment] 2017-05-30 20:41
ah, got it.

Random observation - as far as I can remember the list of projects displayed in the selector appears in alphabetical order. It could be that this is just luck and not guaranteed, or I wonder if perhaps they haven't updated the documentation that you linked to.

**Comment by etanshaul** [comment] 2017-05-30 20:42
ah nevermind - we are sorting it ourselves..

**Comment by nkibler** [comment] 2017-08-31 14:12
Closing this because the project selector actually does return all projects; we currently don't have a problem with the approach taken (block as we loop through calls to the server).

**Closed by nkibler** 2017-08-31 14:12 UTC
Labels: bug, google-account-plugin, Q2 Candidates
