### ISSUE TITLE
Generated Dockerfile doesn't work with Maven plugin

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-intellij#1151] opened 2016-12-07 16:59 UTC
The IntelliJ plugin generates a Dockerfile that contains the line referencing `target.war`.
```
...
ADD target.war $JETTY_BASE/webapps/root.war
```
This works for deploying to App Engine through IntelliJ because it is configured to build `target.war`.
However, it breaks `mvn appengine:deploy` command for users who then want to deploy the project using the appengine-maven-plugin becasue Maven build the application archive based on `{maven module name}.war` pattern.

**Comment by etanshaul** [comment] 2016-12-07 17:46
as discussed, this probably breaks Gradle too when used like this

**Comment by patflynn** [comment] 2016-12-07 19:00
@meltsufin good catch.  This is nasty and should be fixed as part of our flex re-work in January.

**Comment by patflynn** [comment] 2017-05-23 17:53
What about normalizing the name of the archive at staging?  conceivably we
could also let the user specify the final staged archive name/path.

**Comment by etanshaul** [comment] 2017-05-23 17:58
We do currently normalize the name of the archive for staging (we rename it to "target.war/jar"), if I understood you correctly. Doing this, however, lead to the bug described here.

Wouldn't specifying the name also lead to this same issue?

**Comment by etanshaul** [comment] 2017-05-23 20:49
Document a couple of offline discussion points with @patflynn:

- However we decide to support this, we need a migration strategy for users with exiting Dockerfiles with the normalized "target.jar/war" names.
- A potentially first step way to handle build system naming differences is, in the facet config, to give the user the option to change the target artifact name in the Dockerfile, defaulting it to a best guess.

**Comment by chanseokoh** [comment] 2017-05-23 20:55
> A potential first step to handle build system naming differences is, in the facet config, to give the user the option to change the target artifact name in the Dockerfile, defaulting it to a best guess.

Will you allow changing the target name later in the facet config or in the deploy config? If so, I think you need to detect if the Dockerfile is the one you actually generated and not a user-supplied one.

**Comment by etanshaul** [comment] 2017-05-23 20:57
no, only at generation time. at least at first.

**Comment by nkibler** [comment] 2017-06-07 18:03
I'm having trouble understanding the steps to repro this. Is it one of the following?
 
1. You start out with a project that you've added the App Engine facet to through IntelliJ, then you add the App Engine Maven plugin and try running `mvn appengine:deploy`
2. You start out with a Maven project that has the App Engine Maven plugin added, then you try adding the facet through IntelliJ (and generate a Dockerfile), then you try running `mvn appengine:deploy`

**Comment by etanshaul** [comment] 2017-06-07 18:06
Start with an project in IntelliJ, setup flexible support, set app.yaml to a custom runtime, create a Dockerfile and deploy (deploying is optional, but just confirms that it works).

Now, leave the IDE and try to deploy the project via the maven plugin (using the Dockerfile you previously generated). You _should_ be able to reproduce this now.

**Comment by nkibler** [comment] 2017-06-08 00:22
Ok thanks, I've reproduced the issue in a local project.

I've started digging into our options here and I have a quick question: is it acceptable for a user to have to maintain the following statement in their Dockerfile?

```
ADD my-project-1.0-SNAPSHOT.war /webapps/root.war
```

If it's common for a user using this workflow to manage this (e.g. as versions increase, they update this), then why don't we completely step out of their way and stage the WAR/JAR as-is, without renaming to `target.jar/war`? If they opt for a custom runtime, we could simply stage the artifact they're building and the Dockerfile without renaming/modifications and assume their Dockerfile has the right name for the WAR/JAR that's being built.

Staying down the path of using this `target.war/jar` naming scheme for a custom runtime may be tricky.
From what I've seen so far, it's easy to configure the `maven-war-plugin` to output a different WAR name (e.g. `target.war`), but other plugins may depend on the `<artifact>-<version>.war` scheme and might not be configurable in the `pom.xml` (e.g. the `appengine-maven-plugin`).

If we can rely on the user to manage their Dockerfile correctly in this scenario, then the fix is simple.

**Comment by patflynn** [comment] 2017-06-08 14:10
I think the last time I talked to Etan about this we came to the same
conclusion.   I think it's a reasonable first iteration.

other options are:
- give the user some control over what the staged war/jar file will be
called
- support templatizing the source Dockerfile so that the artifact name can
be filtered in at staging time.

This brings to mind this sample I wrote a while back:
https://github.com/patflynn/kplay/blob/master/spring-boot-basic/src/main/docker/Dockerfile

I've seen various java docker build demos where people did similar things,
so I wouldn't be surprised if this becomes a common use-case.

**Comment by nkibler** [comment] 2017-06-08 15:43
I don't think templatizing the Dockerfile will work for us either because I don't see a way to pass Docker build parameters to the invocation underneath the `appengine-maven-plugin`. It could work for us, but it won't solve the problem that other plugins can't use the Dockerfile.

I think the best long-term solution is to give the user control over what archive name is used in the generation of the Dockerfile. But currently, it's impossible for someone to use both our plugin and the `appengine-maven-plugin` off the same Dockerfile. In the short-term, if the user is using a custom runtime, what do you think about:

- Changing the staging code to copy the artifact over without renaming
- Modify the Dockerfile if it references the old `target.jar/war` to reference the artifact that's currently being deployed (so old clients don't break)
- Change the template of newly generated Dockerfiles to have an obvious call-to-action to change the artifact name (e.g. `ADD YOUR_ARTIFACT_NAME.war /webapps/root.war`)

**Comment by etanshaul** [comment] 2017-06-08 16:09
`Modify the Dockerfile if it references the old target.jar/war to reference the artifact that's currently being deployed (so old clients don't break)`

This is a little tricky. The only time we really know the artifact name for sure is at deployment. We could add a migration (which happens when the project loads) that detects this "legacy" artifact name and then updates it to the templatized variable (after showing the user a little dialog).

`Change the template of newly generated Dockerfiles to have an obvious call-to-action to change the artifact name (e.g. ADD YOUR_ARTIFACT_NAME.war /webapps/root.war)`

Agree. We can also have some sort of UI in the facet to configure the Dockerfile artifact reference which would then replace the template variable. Something like a text field underneath "Runtime: custom" which allows the user to type the name in. It could default (shown with some placeholder text) to "auto detected" or something like that (see the next paragraph for what this means).

If the user doesn't update the artifact name then the template variable will remain in place (and other tools won't work with it - but at least the message will be clearer). However, for IJ, at deployment time we _will_ know the artifact name so we can dynamically replace the name at staging time (only for the staged Dockerfile).

Just throwing out ideas. I think we were all saying a lot of the same thing.

**Comment by nkibler** [comment] 2017-06-08 16:42
> We could add a migration (which happens when the project loads)

Couldn't we do it at deployment time instead and without a prompt? Presumably if the Dockerfile references a `target.jar/war`, then we probably generated it and the user didn't modify it. We could silently migrate the file so other plugins will work for them without disruption.

> We can also have some sort of UI in the facet to configure the Dockerfile artifact reference

Yeah, we definitely agree that having additional UI to configure this is ideal. How important is a short-term fix though? I could spend some time on the full proposal instead of coming up with a short-term fix if it's not important.

**Comment by etanshaul** [comment] 2017-06-08 17:05
`Couldn't we do it at deployment time instead and without a prompt?`

Yeah, I think that makes sense.

I could see doing this in a couple phases (doing the UI portion later) as long as the first iteration has some clear messaging (probably in the facet) guiding the user to update the Dockerfile. I don't want to get into a situation where users have to first do a failed deployment before correcting the issue.

**Comment by patflynn** [comment] 2017-06-08 17:07
Let's get in a room and discuss this.

**Comment by nkibler** [comment] 2017-06-08 18:14
To follow up on our conversation offline, we're going to:

- Change newly generated Dockerfiles through IJ to use the `ADD *.jar` and `ADD *.war` syntax
- Stop renaming the built artifacts to `target.jar/war` and leave their names as-is

This will break existing users who have a Dockerfile that has the `ADD target.jar` or `ADD target.war` commands because the built artifact will no longer be renamed. However, any migration scheme we could think of isn't ideal because this is a _source_ migration and it would be difficult to tell whether a Dockerfile needs to be migrated or not.

To combat this, we will make our release notes clear that anyone in this scenario will need to update or regenerate their Dockerfiles.

**Comment by nkibler** [comment] 2017-06-09 15:47
FYI, this is what the error will look like to a user who has a custom Dockerfile referencing a `target.war` after this change:

> Step 2/2 : ADD target.war /webapps/root.war
lstat target.war: no such file or directory
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@..." failed: exit status 1
ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
Failed to deploy '[2017-06-09 08:42:49] appengine-flexible:war. Project: .... Version: auto': Deployment failed with exit code: 1
Please make sure that you are using the latest version of the Google Cloud SDK.
Run ''gcloud components update'' to update the SDK. (See: https://cloud.google.com/sdk/gcloud/reference/components/update.)

**Comment by etanshaul** [comment] 2017-06-28 17:50
moving to the next milestone, as we discussed

**Closed** 2017-09-19 16:30 UTC
Labels: App Engine Flex, bug, google-cloud-tools-plugin
