### ISSUE TITLE
Server returns an error when I start a local dev server in debug mode

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#928] opened 2016-09-22 19:15 UTC
steps to reproduce:

1) checkout this sample https://github.com/GoogleCloudPlatform/cloud-debugger-idea-sample  (probably works with other projects)
2) change the server config to open localhost:8080/hellobrowser
3) start a local debug session
4) observe breakpoint is hit
5) observe that the http response if hellobrowser is:

`bad runtime process port ['']

ERROR: transport error 202: recv failed during handshake: Connection reset by peer
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]`

**Comment by joaoandremartins** [comment] 2016-09-23 17:40
I think this is because your app-engine-java isn't up to date.

Run gcloud components update, get to version 127 and let me know if you're still seeing this.

**Comment by aslo** [comment] 2016-09-23 17:48
Just verified this locally with updated gcloud components.

**Comment by patflynn** [comment] 2016-09-26 13:41
I was on 127

**Comment by joaoandremartins** [comment] 2016-09-26 19:51
@aslo not sure if you've done a lot of work here already, but taking this since it's a bit hi priority for the next release and I've got some bandwidth!

**Comment by aslo** [comment] 2016-09-27 17:42
@joaoandremartins As discussed, I can take this one. Thanks for offering!

**Comment by aslo** [comment] 2016-09-28 19:23
FYI, the cause of this issue is that the local dev server creates multiple java processes in order to simulate auto-scaling. Each of these processes is passed the same jvm arguments (the contents of the `--jvm_flags` argument to dev_appserver.py). 

Since we are currently running the dev_appserver with  
```
--jvm_flags="-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51554,suspend=y,server=n"
```
multiple jvm processes will try to connect to the intellij debugger on the same port, and sometimes none will succeed.

The ideal solution in my mind is to configure the dev_appserver to not spin up more than one java process. (I'm checking if that's possible).

**Comment by chanseokoh** [comment] 2016-09-28 19:31
This might be relevant:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/473

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/473#issuecomment-235789713

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java#L177

**Comment by aslo** [comment] 2016-09-28 20:14
@chanseokoh Thanks for sending those - that's really helpful. Based on the discussion in those issues, it looks like `--max_module_instances=1` would  solve the problem. 

However, I believe this won't fix the issue for multi-module projects. I'll create a separate bug to track that.

**Comment by chanseokoh** [comment] 2016-09-28 21:11
For multiple modules, this could also be interesting, which explains the current state of Eclipse: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/498

**Comment by aslo** [comment] 2016-09-28 21:12
@chanseokoh thanks! FYI I created issue https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/941 to track the multi-module use case:
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/941

**Closed** 2016-09-29 15:18 UTC
Labels: App Engine, bug, google-cloud-tools-plugin, high priority
