### ISSUE TITLE
Sign in button still displays after I signed in.

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-intellij#1730] opened 2017-11-03 15:19 UTC
The GCS project selector still shows a sign in button after I signed in.

![gcs](https://user-images.githubusercontent.com/11820506/32381336-d1c72848-c088-11e7-8f8b-fe5a8458be1b.png)

**Comment by etanshaul** [comment] 2017-11-03 15:24
good catch!

**Comment by etanshaul** [comment] 2017-11-03 16:06
It looks like this happens only on the project selector in the GCS panel. Looking into it.

**Comment by etanshaul** [comment] 2017-11-03 16:24
I suspect this is what is happening:

The project selector when viewed from the GCS panel is unique in that it is not reinitialized on login events. This is because it lives within a side panel that is initialized once on IDE boot.

Other cases of the project selector, like in the deploy config, are reinitialized each time the modal is opened. Similarly, there is no way to log out without first closing this modal - so the next time the modal is re-opened its state will be displayed correctly.

The solution is likely to redraw the state of the project selector bottom button area on login events.

To reproduce:
1) start with the IDE logged out of GCP
2) note the state of the project selector (has a button to sign in)
3) log in to GCP
4) the project selector has not been updated

Note this happens in reverse too: going from logged in to logged out.

**Closed** 2017-11-06 16:49 UTC
