### ISSUE TITLE
Configuring the dev appserver to auto-restart on change seems to break things

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-intellij#972] opened 2016-10-10 17:09 UTC
Steps to reproduce:
1) Create a new app engine project using the wizard
2) configure the development server run config 'on frame deactivation' to 'update resources'
3) start the debugger in debug mode
4) modify index.jsp
5) navigate away from the editor

observed results:
dev server console outputs:
`Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Oct 10, 2016 5:05:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:50447
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:50447/
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:50447/_ah/admin
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
Oct 10, 2016 5:05:39 PM com.google.appengine.tools.development.LocalResourceFileServlet doGet
WARNING: No file found for: /_ah/warmup
INFO     2016-10-10 17:05:39,771 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 404 83
INFO     2016-10-10 17:05:40,183 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,190 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,246 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:05:40,615 module.py:788] default: "GET / HTTP/1.1" 200 113
INFO     2016-10-10 17:06:04,955 module.py:402] [default] Detected file changes:
  /usr/local/google/home/paflynn/IdeaProjects/nowayjose/out/artifacts/nowayjose_war_exploded/index.jsp
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
Disconnected from the target VM, address: '127.0.0.1:45362', transport: 'socket'
ERROR: transport error 202: connect failed: Connection refused
ERROR    2016-10-10 17:06:05,344 http_runtime.py:396] bad runtime process port ['']
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
ERROR    2016-10-10 17:06:05,430 http_proxy.py:116] bad runtime process port ['']
INFO     2016-10-10 17:06:05,446 module.py:402] [default] Detected file changes:
  /usr/local/google/home/paflynn/IdeaProjects/nowayjose/out/artifacts/nowayjose_war_exploded/index.jsp
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
INFO     2016-10-10 17:06:05,531 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 285
ERROR    2016-10-10 17:06:05,827 http_runtime.py:396] bad runtime process port ['']
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]
ERROR    2016-10-10 17:06:05,829 http_proxy.py:116] bad runtime process port ['']
INFO     2016-10-10 17:06:05,930 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 285`

and the browser output is:
`bad runtime process port ['']

ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:750]`

**Comment by chanseokoh** [comment] 2016-10-10 17:42
This seems like the same issue fixed in Eclipse: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/604

The root cause of the issue is the IDE not being able to accept new, multiple socket connections from JVMs, which also affected #928. (Corresponding Eclipse issue: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/473)

I'm guessing ultimately fixing #941 would also fix this issue.

**Comment by joaoandremartins** [comment] 2016-10-10 18:45
@chanseokoh if I understand correctly, your suggested solution is to set the max module instances to 1, which we're already doing and allows us to run dev_appserver on debug mode. That solution isn't working for the case where the dev_appserver instance is restarted with the new code, though.

Let me know if there's anything I'm missing.

**Comment by briandealwis** [comment] 2016-10-10 18:48
@joaoandremartins in Eclipse, the server socket was closed after the first connection.  We had to change the underlying Eclipse code to support keeping the server socket open for the duration of the launch so that there was still a socket for the restarted modules to re-connect to.

**Comment by chanseokoh** [comment] 2016-10-10 18:58
Correct me if I'm wrong @briandealwis:

@joaoandremartins I think setting the max module instances to 1 is a slightly different issue (although there exists some commonality in the root cause), and the fix is in fact like a temporary workaround. This workaround also doesn't support multiple services/modules as @aslo said in #941. By limiting the module instance to 1, we avoid the situation JVMs trying to making multiple connections to the IDE. I believe the IDE not being able to accept multiple connections (for whatever reasons) is the root cause.

The issue described here is also because of this root cause. When the dev server detects changes in an app, it restarts itself and tries to make a new connection to the IDE. So, setting the max module can't avoid this.

**Comment by briandealwis** [comment] 2016-10-10 19:52
Exactly right.

**Comment by joaoandremartins** [comment] 2016-10-13 23:11
After looking at IJ source code for 2 or 3 days, I think I know what's happening.

The debug server VM is brought up when the debug session starts, but is brought down and disposed of when hotswap happens and it doesn't come back up. A debug restart is required.

A possible explanation for this is that IJ's debug server VM isn't expecting the debuggee VM to go down during hotswap, and must assume debugging is done when the debug connection is interrupted. Interestingly enough though, the debug session itself isn't terminated and stays up...

There are two possible solutions for this issue:

1) Have dev_appserver.py spawn a proxy JVM that is always alive during the time the debuggee VMs are down swapping code,

2) Come up with a way of having IJ's debug server staying alive and listening to new connections even after previous connections were interrupted. I think Eclipse's solution was of this kind, as they set the socket to stay alive for any number of connections. However, things seem to be a bit different in IJ, as something else is explicitly disposing of the debug server VM.

I filed an issue with IJ on https://youtrack.jetbrains.com/issue/IDEA-162577 to know whether there's any way of telling the debug server to stay up.

We should probably also look into why the debuggee VMs are going down, if hotswap allows them to stay up.

**Closed** 2016-10-18 22:26 UTC
Labels: App Engine, bug, google-cloud-tools-plugin, high priority
