### ISSUE TITLE
Deployment UI should display error message if no deployable (artifact) is selected

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/google-cloud-intellij#913] opened 2016-09-16 20:45 UTC
With a Flex app, I'm being able to create a Deployment run config in a module without any artifacts. No deployable is selectable and no warning is shown.

![no-deployable](https://cloud.githubusercontent.com/assets/3290856/18600669/ee787286-7c2c-11e6-9b3c-1b890e2cdba9.png)

However, when you try to run it, it produces an error window.

![deployerror](https://cloud.githubusercontent.com/assets/3290856/18600686/00155676-7c2d-11e6-84a9-1aee1f4bbf81.png)

We should probably be complaining in the UI if no deployable is selected.

**Comment by joaoandremartins** [comment] 2016-09-16 21:27
Turns out I got my project into this weird state, and I can't reproduce it...

Will reopen if I can reproduce. Unless you want to repurpose this as you mentioned, @etanshaul

**Comment by etanshaul** [comment] 2016-09-16 21:29
nah lets just close this one (assuming you are comfortable that its not reproducible) since its pretty different then what I had in mind.

**Closed** 2016-09-16 21:38 UTC
